---
fail_fast: false
repos:
  - repo: https://github.com/standard/standard
    rev: v16.0.4
    hooks:
      - id: standard
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: fix-byte-order-marker
    - id: mixed-line-ending
    - id: check-merge-conflict
    - id: check-case-conflict
