name: WYOA Release

on:
  workflow_dispatch:

# Detect which folders in project-root (which contain the containers) contain changes
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Define if tests and push should be run against which versions/platforms
    - name: Prepare
      id: prep
      run: |
        VERSION=$(cat ./apps/wyoa-bot/VERSION)
        PLATFORM=$(cat ./apps/wyoa-bot/PLATFORM)
        if [ "${{github.event_name}}" == "pull_request" ]; then
          echo ::set-output name=push::false
          echo ::set-output name=cache_from::"type=local,src=/tmp/.buildx-cache"
          echo ::set-output name=cache_to::""
        else
          echo ::set-output name=push::true
          echo ::set-output name=cache_from::"type=local,src=/tmp/.buildx-cache"
          echo ::set-output name=cache_to::"type=local,dest=/tmp/.buildx-cache,mode=max"
        fi

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64

    - name: Login to GHCR
      uses: docker/login-action@v1
      if: github.event_name != 'pull_request'
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Install and configure Buildx
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
        install: true
        version: latest
        driver-opts: image=moby/buildkit:latest

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ghcr.io/${{ github.repository_owner }}/wyoa-bot
        restore-keys: |
          ghcr.io/${{ github.repository_owner }}/wyoa-bot

    # Creates a local build to run tests on
    - name: Build and Load local test-container
      if: ${{ steps.prep.outputs.goss == 'true' }}
      uses: docker/build-push-action@v2
      with:
        build-args: VERSION=${{ steps.prep.outputs.version }}
        context: .
        file: ./${{ steps.prep.outputs.category }}/wyoa-bot/Dockerfile
        load: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/wyoa-bot:test
        cache-from: ${{ steps.prep.outputs.cache_from }}
        cache-to: ${{ steps.prep.outputs.cache_to }}

    # Run GOSS tests if included with the container
    - name: Run GOSS tests
      if: ${{ steps.prep.outputs.goss == 'true' }}
      env:
        GOSS_FILE: ./${{ steps.prep.outputs.category }}/wyoa-bot/goss.yaml
      run: |
        dgoss run ghcr.io/${{ github.repository_owner }}/wyoa-bot:test

    # Push if not a PR, otherwise just test the build process for all requested platforms
    - name: Build and Push
      uses: docker/build-push-action@v2
      with:
        build-args: VERSION=${{ steps.prep.outputs.version }}
        context: .
        platforms: ${{ steps.prep.outputs.platform }}
        file: ./${{ steps.prep.outputs.category }}/wyoa-bot/Dockerfile
        push: ${{ steps.prep.outputs.push }}
        tags: |
          ghcr.io/${{ github.repository_owner }}/wyoa-bot:latest
          ghcr.io/${{ github.repository_owner }}/wyoa-bot:v${{ steps.prep.outputs.version }}
        cache-from: ${{ steps.prep.outputs.cache_from }}
        cache-to: ${{ steps.prep.outputs.cache_to }}
